<?xml version="1.0" encoding="UTF-8"?>
<!--
  * registry/registry/siteSettings.xml
  *
  * Copyright (c) 2014-2015 Simon Fraser University Library
  * Copyright (c) 2003-2015 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Default site settings.
  -->

<!DOCTYPE site_settings [
	<!ELEMENT site_settings (setting+)>
	<!ELEMENT setting (name, value)>
	<!ATTLIST setting type (int|string|object|bool) #REQUIRED>
	<!ATTLIST setting locale (0|1) #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT value (#PCDATA | array)*>
	<!ELEMENT element (#PCDATA | array)*>
	<!ATTLIST element key CDATA #IMPLIED>
	<!ELEMENT array (element+)>
]>

<site_settings>
	<setting type="string" locale="1">
		<name>contactName</name>
		<value>{translate key="common.openMonographPress"}</value>
	</setting>
	<setting type="string" locale="1">
		<name>contactEmail</name>
		<value>{$contactEmail}</value>
	</setting>
</site_settings>
